### POD 1
# Leafs
leaf_1_1[0]="A"
leaf_1_1[1]="B"
leaf_1_1[2]="C"


# Spines
spine_1_1[0]="A"
spine_1_1[1]="D"
spine_1_1[2]="G"
spine_1_1[3]="H"
spine_1_2[0]="B"
spine_1_2[1]="E"
spine_1_2[2]="I"
spine_1_2[3]="J"

# Servers
server_1_1[0]="C"
server_1_1[1]="AA"
server_1_1[2]="AB"
server_1_2[0]="Z"
server_1_2[1]="AC"
server_1_2[2]="AD"

# Containers
container_1_1_1[0]="AA/00:00:00:01:01:01"
container_1_1_2[0]="AA/00:00:00:01:01:02"
container_1_1_3[0]="AB/00:00:00:01:01:03"
container_1_2_1[0]="AC/00:00:00:01:02:01"
container_1_2_2[0]="AD/00:00:00:01:02:02"

### POD 2
# Leafs
leaf_2_1[0]="K"
leaf_2_1[1]="L"
leaf_2_1[2]="M"
leaf_2_2[0]="N"
leaf_2_2[1]="O"
leaf_2_2[2]="W"

# Spines
spine_2_1[0]="K"
spine_2_1[1]="N"
spine_2_1[2]="Q"
spine_2_1[3]="R"
spine_2_2[0]="L"
spine_2_2[1]="O"
spine_2_2[2]="S"
spine_2_2[3]="T"

# Servers

server_2_2[0]="W"
server_2_2[1]="AF"

# Containers
container_2_1_1[0]="AE/00:00:00:02:01:01"
container_2_2_1[0]="AF/00:00:00:02:02:01"

## CORE SWITCHES
core_1_1[0]="G"
core_1_1[1]="I"
core_1_1[2]="Q"
core_1_1[3]="S"
core_1_2[0]="H"
core_1_2[1]="J"
core_1_2[2]="R"
core_1_2[3]="T"

# Multipath policy
core_1_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
core_1_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spine_1_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spine_1_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spine_2_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spine_2_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_1_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_1_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_2_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_2_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"

# Image definitions
core_1_1[image]="kathara/frr"
core_1_2[image]="kathara/frr"
spine_1_1[image]="kathara/frr"
spine_1_2[image]="kathara/frr"
spine_2_1[image]="kathara/frr"
spine_2_2[image]="kathara/frr"
leaf_1_1[image]="kathara/frr"
leaf_1_2[image]="kathara/frr"
leaf_2_1[image]="kathara/frr"
leaf_2_2[image]="kathara/frr"
server_1_1[image]="kathara/base"
server_1_2[image]="kathara/base"
server_2_1[image]="kathara/base"
server_2_2[image]="kathara/base"
container_1_1_1[image]="kathara/base"
container_1_1_2[image]="kathara/base"
container_1_1_3[image]="kathara/base"
container_1_2_1[image]="kathara/base"
container_1_2_2[image]="kathara/base"
container_2_1_1[image]="kathara/base"
container_2_2_1[image]="kathara/base"

# Enable IPv6 for FRR unumbered interfaces
core_1_2[ipv6]="True"
core_1_1[ipv6]="True"
spine_1_1[ipv6]="True"
spine_1_2[ipv6]="True"
spine_2_1[ipv6]="True"
spine_2_2[ipv6]="True"
leaf_1_1[ipv6]="True"
leaf_1_2[ipv6]="True"
leaf_2_1[ipv6]="True"
leaf_2_2[ipv6]="True"