# AS30 devices

dns1[image]="kathara/frr"


as30r1[image]="kathara/frr"

# AS20 devices
as20r1[0]="B"
as20r1[1]="C"
as20r1[2]="E"
as20r1[image]="kathara/frr"

# AS40 devices
as40r1[0]="C"
as40r1[1]="D"
as40r1[image]="kathara/frr"

c1[0]="D"
c1[image]="kathara/base"

# AS1 devices
as1rome[0]="E"
as1rome[1]="G"
as1rome[2]="F"
as1rome[image]="kathara/frr"

as1stockholm[0]="I"
as1stockholm[1]="G"
as1stockholm[2]="H"
as1stockholm[image]="kathara/frr"

as1madrid[0]="N"
as1madrid[1]="H"
as1madrid[2]="F"
as1madrid[image]="kathara/frr"

# AS50 devices
as50r1[0]="I"
as50r1[1]="L"
as50r1[image]="kathara/frr"

# AS60 devices
as60r1[0]="L"
as60r1[1]="M"
as60r1[image]="kathara/frr"

c2[0]="M"
c2[image]="kathara/base"

# AS70 devices

as70r1[image]="kathara/frr"

dns2[image]="kathara/frr"

# AS90 devices
as90r1[0]="O"
as90r1[1]="Q"
as90r1[image]="kathara/frr"

c3[0]="Q"
c3[image]="kathara/base"