apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-dply
  namespace: llm-ns
spec:
  selector:
    matchLabels:
      app: llm
  replicas: 1
  template:
    metadata:
      labels:
        app: llm
    spec:
      restartPolicy: Always
      containers:
        - name: llm-container
          image: ik2227/llama2
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          env:
            - name: LLAMA_SYS_PROMPT
              value: "Once upon a time,"
            - name: ENABLE_RDMA
              value: "true"
            - name: RXE_IFACE
              value: "rxe1"
          volumeMounts:
            - mountPath: /data/roce
              name: roce-client
            - mountPath: /dev/infiniband
              name: ib
      volumes:
        - name: roce-client
          hostPath:
            path: /shared/roce
        - name: ib
          hostPath:
            path: /dev/infiniband
      nodeSelector:
        supports: rdma
