router bgp 20
  no bgp ebgp-requires-policy

  neighbor 10.20.30.2 remote-as 30
  neighbor 10.20.30.2 description as30r1 Router
  neighbor 10.20.40.2 remote-as 40
  neighbor 10.20.40.2 description as40r1 Router
  neighbor 10.1.20.2 remote-as 1
  neighbor 10.1.20.2 description rome Router