router bgp 1
  no bgp ebgp-requires-policy

  neighbor 10.1.50.1 remote-as 50
  neighbor 10.1.50.1 description as50r1 Router
  neighbor 10.1.3.2 remote-as 1
  neighbor 10.1.3.2 description as1rome Router
  neighbor 10.1.2.2 remote-as 1
  neighbor 10.1.2.2 description as1madrid Router