router bgp 40
  no bgp ebgp-requires-policy

  neighbor 10.1.40.2 remote-as 1
  neighbor 10.1.40.2 description as1r1 Router
  neighbor 10.40.50.1 remote-as 50
  neighbor 10.40.50.1 description as50r1 Router
  neighbor 10.40.0.2 remote-as 40
  neighbor 10.40.0.2 description dns2 Dns

  network 10.40.0.0/30