router bgp 1
  no bgp ebgp-requires-policy

  neighbor 10.1.70.1 remote-as 70
  neighbor 10.1.70.1 description as70r1 Router
  neighbor 10.1.2.1 remote-as 1
  neighbor 10.1.2.1 description as1stockholm Router
  neighbor 10.1.1.2 remote-as 1
  neighbor 10.1.1.2 description as1rome Router