router bgp 50
  no bgp ebgp-requires-policy

  neighbor 10.1.50.2 remote-as 1
  neighbor 10.1.50.2 description stockholm Router
  neighbor 10.20.30.2 description as30r1 Router
  neighbor 10.50.60.2 remote-as 60
  neighbor 10.50.60.2 description as60r1 Router